In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [25]:
 a=np.ones(2)
print(a)

[1. 1.]


In [14]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [16]:
b=np.empty(3)
print(b)

[9.45502430e-312 0.00000000e+000 2.22520627e-307]


In [23]:
c=np.linspace(0,10,5)
print(c)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
np.sort(a)
print(a)

[0 0 0 0 0]


In [27]:
arr=np.array([5,1,3,11,9])
np.sort(arr)


array([ 1,  3,  5,  9, 11])

In [28]:
print(arr)

[ 5  1  3 11  9]


In [40]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
np.concatenate((x,y),axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
x1=np.array([[1,2],[3,4],[5,6]])
y1=np.array([[11,22],[33,44]])
np.concatenate((x1,y1),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 22],
       [33, 44]])

In [44]:
np.concatenate((x1,y1),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [11, 22],
       [33, 44]])

In [49]:
x1.shape

(3, 2)

In [63]:
x.shape

(5,)